# AdaBoost

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_recall_fscore_support,roc_curve,auc,accuracy_score,classification_report, confusion_matrix
from scipy.stats.mstats import gmean
from sklearn.datasets import make_circles
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_moons
from sklearn.preprocessing import Normalizer,MinMaxScaler,StandardScaler
import numpy as np
import os
import pandas as pd
import numpy.matlib
from numpy import random
import os
import math

from sklearn.metrics import auc
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import f1_score

import warnings
warnings.filterwarnings("ignore")


In [2]:
def fit_boosting(X, y, n_estimators=10):
    n_samples, n_features = X.shape
    D = np.ones((n_samples, ))
    estimators = []

    for t in range(n_estimators):
        D = D / np.sum(D)                   

        h = DecisionTreeClassifier(max_depth=5)  
        h.fit(X, y, sample_weight=D)        

        ypred = h.predict(X)   
        e = 1 - accuracy_score(y, ypred, sample_weight=D)  
        if e==0.0:
            e=0.000000000001
        if e==1.0:
            e=0.9999
        a = 0.5 * np.log((1 - e) / e)               

        m = (y == ypred) * 1 + (y != ypred) * -1    
        D *= np.exp(-a * m)
                 
        estimators.append((a, h))  

    return estimators
def predict_boosting(X, estimators):
    pred = np.zeros((X.shape[0], ))
    y_proba = np.zeros((X.shape[0], ))

    for a, h in estimators:
        pred += a * h.predict(X)
        y_proba+= h.predict_proba(X)[:, 1] 

    y = np.sign(pred)

    return y , (y_proba/len(estimators))

In [ ]:
#data_name='vehicle0.dat'
data_name='glass1.dat'
Size_data=846
C_maj=647
F_maj=18
C_min=199
F_min=18
head=23 # number of line without sample (header)

if data_name=='glass1.dat':
    Size_data=214
    C_maj=138
    F_maj=9
    C_min=76
    F_min=9
    head=14 # index of first data sample

if data_name=='ecoli1.dat':
    Size_data=336
    C_maj=259
    F_maj=7
    C_min=77
    F_min=7
    head=12 # index of first data sample
if data_name=='ecoli4.dat':
    Size_data=336
    C_maj=316
    F_maj=7
    C_min=20
    F_min=7
    head=12 # index of first data sample

if data_name=='glass4.dat':
    Size_data=214
    C_maj=201
    F_maj=9
    C_min=13
    F_min=9
    head=14 # index of first data sample
if data_name=='yeast-2_vs_8.dat':
    Size_data=482
    C_maj=462
    F_maj=8
    C_min=20
    F_min=8
    head=13 # index of first data sample

if data_name=='yeast4.dat':
    Size_data=1484
    C_maj=1433
    F_maj=8
    C_min=51
    F_min=8
    head=13 # index of first data sample
if data_name=='yeast-1-2-8-9_vs_7.dat':
    Size_data=947
    C_maj=917
    F_maj=8
    C_min=30
    F_min=8
    head=13 # index of first data sample

if data_name=='yeast5.dat':
    Size_data=1484
    C_maj=1440
    F_maj=8
    C_min=44
    F_min=8
    head=13 # index of first data sample 

if data_name=='abalone9-18.dat':
    Size_data=731
    C_maj=689
    F_maj=8
    C_min=42
    F_min=8
    head=13 # index of first data sample 

   
    
if data_name=='page-blocks-1-3_vs_4.dat':
    Size_data=472
    C_maj=444
    F_maj=10
    C_min=28
    F_min=10
    head=15 # index of first data sample 


if data_name=='glass-0-1-2-3_vs_4-5-6.dat':
    Size_data=214
    C_maj=163
    F_maj=9
    C_min=51
    F_min=9
    head=14 # index of first data sample  
    
if data_name=='glass0.dat':
    Size_data=214
    C_maj=144
    F_maj=9
    C_min=70
    F_min=9
    head=14 # index of first data sample     
  
if data_name=='vehicle3.dat':
    Size_data=846
    C_maj=634
    F_maj=18
    C_min=212
    F_min=18
    head=23 # index of first data sample     
if data_name=='ecoli2.dat':
    Size_data=336
    C_maj=284
    F_maj=7
    C_min=52
    F_min=7
    head=12 # index of first data sample 
if data_name=='yeast6.dat':
    Size_data=1484
    C_maj=1449
    F_maj=8
    C_min=35
    F_min=8
    head=13 # index of first data sample   
  
if data_name=='yeast-2_vs_4.dat':
    Size_data=514
    C_maj=463
    F_maj=8
    C_min=51
    F_min=8
    head=13 # index of first data sample    

if data_name=='yeast3.dat':
    Size_data=1484
    C_maj=1321
    F_maj=8
    C_min=163
    F_min=8
    head=13 # index of first data sample     

    
if data_name=='yeast-1-4-5-8_vs_7.dat':
    Size_data=693
    C_maj=663
    F_maj=8
    C_min=30
    F_min=8
    head=13 # index of first data sample     
if data_name=='segment0.dat':
    Size_data=2308
    C_maj=1979
    F_maj=19
    C_min=329
    F_min=19
    head=24 # index of first data sample 

if data_name=='yeast-0-5-6-7-9_vs_4.dat':
    Size_data=528
    C_maj=477
    F_maj=8
    C_min=51
    F_min=8
    head=13 # index of first data sample 

if data_name=='ecoli3.dat':
    Size_data=336
    C_maj=301
    F_maj=7
    C_min=35
    F_min=7
    head=12 # index of first data sample 
if data_name=='vowel0.dat':
    Size_data=988
    C_maj=898
    F_maj=13
    C_min=90
    F_min=13
    head=18 # index of first data sample 

if data_name=='glass2.dat':
    Size_data=214
    C_maj=197
    F_maj=9
    C_min=17
    F_min=9
    head=14 # index of first data sampl
if data_name=='glass5.dat':
    Size_data=214
    C_maj=205
    F_maj=9
    C_min=9
    F_min=9
    head=14 # index of first data sample 
    
if data_name=='glass6.dat':
    Size_data=214
    C_maj=185
    F_maj=9
    C_min=29
    F_min=9
    head=14 # index of first data sample 

if data_name=='new-thyroid1.dat':
    Size_data=215
    C_maj=180
    F_maj=5
    C_min=35
    F_min=5
    head=10 # index of first data sample
    
if data_name=='ecoli-0_vs_1.dat':
    Size_data=220
    C_maj=77
    F_maj=7
    C_min=143
    F_min=7
    head=12 # index of first data sample 
if data_name=='wisconsin.dat':
    Size_data=683
    C_maj=444
    F_maj=9
    C_min=239
    F_min=9
    head=14 # index of first data sample 
if data_name=='iris0.dat':
    Size_data=150
    C_maj=100
    F_maj=4
    C_min=50
    F_min=4
    head=9 # index of first data sample 
    
if data_name=='haberman.dat':
    Size_data=306
    C_maj=225
    F_maj=3
    C_min=81
    F_min=3
    head=8 # index of first data sample   
    
data_maj = np.zeros((C_maj,F_maj))
labels_maj = np.zeros((C_maj,))
data_min = np.zeros((C_min,F_min))
labels_min = np.zeros((C_min,))

f1=0
f2=0   
with open( data_name,'r') as file:
    a = file.readlines()
    print(a[0:head])
    for i in range(Size_data):
        a[i+head] = a[i+head].replace(" ","")
        b = a[i+head].split(',')
        print(i,b)
        if b[0]=='M':
            b[0]=0
        if b[0]=='F':
            b[0]=1
        if b[0]=='I':
            b[0]=2
        if b[F_maj].rfind("positive")!=(-1):
            b[F_maj] = -1
            data_min[f2,:] = np.array(b[:F_maj])
            labels_min[f2] = b[F_maj] 
            f2+=1
        elif b[F_maj].rfind("negative")!=(-1):
            b[F_maj] = 1
            data_maj[f1,:] = np.array(b[:F_maj])
            labels_maj[f1] = b[F_maj] 
            f1+=1
print(f1,f2)
'''Xtrn_maj, Xtst_maj, ytrn_maj, ytst_maj = train_test_split(data_maj, labels_maj, test_size=0.25, random_state=13)
Xtrn_min, Xtst_min, ytrn_min, ytst_min = train_test_split(data_min, labels_min, test_size=0.25, random_state=13)
scl = StandardScaler()
data_train=scl.fit_transform(np.vstack((Xtrn_min,Xtrn_maj)))
data_test = scl.transform(np.vstack((Xtst_min,Xtst_maj)))
features_min=data_train[0:len(Xtrn_min),:]
features_maj=data_train[len(Xtrn_min):,:] '''

In [4]:
from sklearn.model_selection import KFold
from imblearn.metrics import geometric_mean_score
data=np.vstack((data_min,data_maj))
labels=np.hstack((labels_min,labels_maj))
kf = KFold(n_splits=5,random_state=76,shuffle=True) # 5fold cross validation
k_g_mean=[]
k_roc=[]
k_PR=[]
k_imb_g=[]
scl = StandardScaler()
for train_index, test_index in kf.split(data):

        data_train=scl.fit_transform(data[train_index])
        data_test=scl.transform(data[test_index])
        ytrn=labels[train_index]
        ytst=labels[test_index]
        estimators = fit_boosting(data_train, ytrn, 10)
        predictions, y_proba=predict_boosting(data_test, estimators)
        print("Confusion Matrix:")
        print(confusion_matrix(ytst, predictions))
        print()
        print("Classification Report")
        print(classification_report(ytst, predictions))
        roc_auc= roc_auc_score(ytst, y_proba)
        precision, recall, thresholds = precision_recall_curve(ytst, y_proba)
        PR_auc_score = auc(recall, precision)
        print(roc_auc,PR_auc_score)
        g_mean = 1.0
        for label in np.unique(ytst):
            idx = (ytst== label)
            ytest=np.array(ytst)
            preds=np.array(predictions)
            g_mean *= accuracy_score(ytest[idx], predictions[idx])
        g_mean = np.sqrt(g_mean)
        g=geometric_mean_score(ytst, predictions, average='macro')
        k_imb_g.append(g)
        print( g_mean,"***********",g)
        k_g_mean.append(g_mean)
        k_roc.append(roc_auc)
        k_PR.append(PR_auc_score)

    

print("G_means: ", k_g_mean, "Mean:",np.array(k_g_mean).mean())
print("G_means: ", k_imb_g, "Mean:",np.array(k_imb_g).mean())
print("roc_auc: ", k_roc, "Mean:",np.array(k_roc).mean())
print("PR_auc_score: ", k_PR, "Mean:",np.array(k_PR).mean())

Confusion Matrix:
[[ 0  1]
 [ 0 31]]

Classification Report
              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00         1
         1.0       0.97      1.00      0.98        31

    accuracy                           0.97        32
   macro avg       0.48      0.50      0.49        32
weighted avg       0.94      0.97      0.95        32

1.0 1.0
0.0 *********** 0.5
Confusion Matrix:
[[ 0  2]
 [ 1 29]]

Classification Report
              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00         2
         1.0       0.94      0.97      0.95        30

    accuracy                           0.91        32
   macro avg       0.47      0.48      0.48        32
weighted avg       0.88      0.91      0.89        32

0.45 0.962399193548387
0.0 *********** 0.48333333333333334
Confusion Matrix:
[[ 1  2]
 [ 0 29]]

Classification Report
              precision    recall  f1-score   support

        -1.0       1.00 

ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.